name: Upload-To-S3

on: [push]

env:
  AWS_ENDPOINT: https://s3-ti.tinext.cloud

jobs:
  upload-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Sync files to S3 bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          AWS_BUCKET: files.banana.ch
        run: |
          aws s3 sync --delete --dryrun \
            --endpoint-url ${{ env.AWS_ENDPOINT }} \
            --exclude ".git*" \
            --exclude "*.gitignore" \
            . s3://$S3_BUCKET/portal/repodata/ghba/Switzerland
